<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; The Simplex Method – S&amp;DS 431/631 — Optimization and Computation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../lectures/11-lp-duality.html" rel="next">
<link href="../lectures/09-lp-formulation-geometry.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1db14e1c4cc35bfe1d9badc9e4551eed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-434abab37f7d394f280d9c89d7fbc13f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
// Plotly Warmtone theming helpers — shared across all lectures
// Reads CSS custom properties set by _warmtone.scss (light/dark aware)
const plotlyConfig = {responsive: true, displayModeBar: false};
const figFont = "'Palatino Linotype', 'Book Antiqua', Palatino, Georgia, serif";
const figFontHeading = "'Palatino Linotype', 'Book Antiqua', Palatino, Georgia, serif";

function css(v) {
  return getComputedStyle(document.documentElement).getPropertyValue(v).trim();
}

function legendStyle() {
  return {
    font: {family: figFont, size: 13, color: css('--fig-text')},
    bgcolor: css('--fig-bg') + 'dd',
    bordercolor: css('--fig-grid'),
    borderwidth: 1,
  };
}

function themeLayout(extra) {
  return Object.assign({
    paper_bgcolor: css('--fig-bg'),
    plot_bgcolor: css('--fig-plot-bg'),
    font: {family: figFont, color: css('--fig-text'), size: 14},
  }, extra || {});
}

function themeAxis(title, extra) {
  return Object.assign({
    title: {text: title, font: {family: figFont, size: 14}},
    gridcolor: css('--fig-grid'),
    zerolinecolor: css('--fig-grid'),
    linecolor: css('--fig-axis'),
    tickfont: {family: figFont, size: 12, color: css('--fig-axis')},
  }, extra || {});
}

// Plotly color sequences matching the Warmtone palette
const warmtonePalette = [
  '#2e86c1', '#d45d5d', '#27ae60', '#e67e22', '#8e44ad',
  '#2c3e50', '#16a085', '#c0392b', '#2980b9', '#f39c12'
];
</script>
<script src="https://cdn.plot.ly/plotly-2.35.0.min.js" charset="utf-8"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lectures/09-lp-formulation-geometry.html">Linear Programming</a></li><li class="breadcrumb-item"><a href="../lectures/10-simplex-method.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Simplex Method</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">S&amp;DS 431/631 — Optimization and Computation</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Preparation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction and Motivation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/02-math-background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Mathematical Background</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Convex Optimization Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/03-convex-sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Convex Sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/04-convex-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Convex Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/05-convex-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Convex Optimization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">First-Order Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/06-gradient-descent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">A Primer of Unconstrained Optimization: Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/07-momentum-adaptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Momentum and Adaptive Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/08-sgd-proximal-frank-wolfe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">SGD, Proximal Gradient, and Frank-Wolfe</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear Programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/09-lp-formulation-geometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">LP Formulation and Geometry</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/10-simplex-method.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Simplex Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/11-lp-duality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">LP Duality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/12-dual-simplex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">The Dual Simplex Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/13-lp-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">LP Applications and Game Theory</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Second-Order and Interior Point Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/14-newton-method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Newton’s Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/15-ellipsoid-method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Ellipsoid Method</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/16-interior-point-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interior Point Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Modern Computation Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/17-diffusion-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Diffusion Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/18-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Summary</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-will-be-covered" id="toc-what-will-be-covered" class="nav-link active" data-scroll-target="#what-will-be-covered">What Will Be Covered</a></li>
  <li><a href="#sec-equational-form" id="toc-sec-equational-form" class="nav-link" data-scroll-target="#sec-equational-form"><span class="header-section-number">10.1</span> From Canonical to Equational Form</a></li>
  <li><a href="#sec-derivation" id="toc-sec-derivation" class="nav-link" data-scroll-target="#sec-derivation"><span class="header-section-number">10.2</span> Deriving the Simplex Method</a>
  <ul class="collapse">
  <li><a href="#sec-setup" id="toc-sec-setup" class="nav-link" data-scroll-target="#sec-setup"><span class="header-section-number">10.2.1</span> Setup and Notation</a></li>
  <li><a href="#sec-starting-bfs" id="toc-sec-starting-bfs" class="nav-link" data-scroll-target="#sec-starting-bfs"><span class="header-section-number">10.2.2</span> Starting from a BFS</a></li>
  <li><a href="#sec-reduced-costs" id="toc-sec-reduced-costs" class="nav-link" data-scroll-target="#sec-reduced-costs"><span class="header-section-number">10.2.3</span> Reduced Costs</a></li>
  <li><a href="#sec-optimality" id="toc-sec-optimality" class="nav-link" data-scroll-target="#sec-optimality"><span class="header-section-number">10.2.4</span> Optimality Condition</a></li>
  <li><a href="#sec-pivot-mechanism" id="toc-sec-pivot-mechanism" class="nav-link" data-scroll-target="#sec-pivot-mechanism"><span class="header-section-number">10.2.5</span> The Pivot Mechanism</a></li>
  <li><a href="#sec-simplex-algorithm" id="toc-sec-simplex-algorithm" class="nav-link" data-scroll-target="#sec-simplex-algorithm"><span class="header-section-number">10.2.6</span> The Simplex Algorithm</a></li>
  <li><a href="#sec-why-simplex" id="toc-sec-why-simplex" class="nav-link" data-scroll-target="#sec-why-simplex"><span class="header-section-number">10.2.7</span> Why the Simplex Method Works</a></li>
  </ul></li>
  <li><a href="#sec-tableau" id="toc-sec-tableau" class="nav-link" data-scroll-target="#sec-tableau"><span class="header-section-number">10.3</span> The Simplex Tableau</a>
  <ul class="collapse">
  <li><a href="#sec-tableau-setup" id="toc-sec-tableau-setup" class="nav-link" data-scroll-target="#sec-tableau-setup"><span class="header-section-number">10.3.1</span> Tableau Quantities</a></li>
  <li><a href="#sec-dictionary" id="toc-sec-dictionary" class="nav-link" data-scroll-target="#sec-dictionary"><span class="header-section-number">10.3.2</span> The Dictionary Form</a></li>
  <li><a href="#sec-tableau-layout" id="toc-sec-tableau-layout" class="nav-link" data-scroll-target="#sec-tableau-layout"><span class="header-section-number">10.3.3</span> The Tableau Layout</a></li>
  <li><a href="#sec-pivoting" id="toc-sec-pivoting" class="nav-link" data-scroll-target="#sec-pivoting"><span class="header-section-number">10.3.4</span> Pivoting in Tableau Notation</a></li>
  </ul></li>
  <li><a href="#sec-full-algorithm" id="toc-sec-full-algorithm" class="nav-link" data-scroll-target="#sec-full-algorithm"><span class="header-section-number">10.4</span> The Full Simplex Algorithm (Tableau Form)</a></li>
  <li><a href="#sec-example" id="toc-sec-example" class="nav-link" data-scroll-target="#sec-example"><span class="header-section-number">10.5</span> Worked Example</a></li>
  <li><a href="#sec-initialization" id="toc-sec-initialization" class="nav-link" data-scroll-target="#sec-initialization"><span class="header-section-number">10.6</span> Simplex Initialization via Auxiliary LP</a>
  <ul class="collapse">
  <li><a href="#sec-aux-idea" id="toc-sec-aux-idea" class="nav-link" data-scroll-target="#sec-aux-idea"><span class="header-section-number">10.6.1</span> The Key Idea</a></li>
  <li><a href="#sec-aux-why" id="toc-sec-aux-why" class="nav-link" data-scroll-target="#sec-aux-why"><span class="header-section-number">10.6.2</span> Why This Works</a></li>
  <li><a href="#sec-init-algorithm" id="toc-sec-init-algorithm" class="nav-link" data-scroll-target="#sec-init-algorithm"><span class="header-section-number">10.6.3</span> The Initialization Algorithm</a></li>
  <li><a href="#sec-aux-example" id="toc-sec-aux-example" class="nav-link" data-scroll-target="#sec-aux-example"><span class="header-section-number">10.6.4</span> Example</a></li>
  </ul></li>
  <li><a href="#sec-pivoting-rules" id="toc-sec-pivoting-rules" class="nav-link" data-scroll-target="#sec-pivoting-rules"><span class="header-section-number">10.7</span> Pivoting Rules</a>
  <ul class="collapse">
  <li><a href="#sec-dantzig" id="toc-sec-dantzig" class="nav-link" data-scroll-target="#sec-dantzig"><span class="header-section-number">10.7.1</span> Dantzig’s Rule</a></li>
  <li><a href="#sec-degeneracy" id="toc-sec-degeneracy" class="nav-link" data-scroll-target="#sec-degeneracy"><span class="header-section-number">10.7.2</span> Degeneracy and Cycling</a></li>
  <li><a href="#sec-bland" id="toc-sec-bland" class="nav-link" data-scroll-target="#sec-bland"><span class="header-section-number">10.7.3</span> Bland’s Rule</a></li>
  <li><a href="#sec-oracle-complexity" id="toc-sec-oracle-complexity" class="nav-link" data-scroll-target="#sec-oracle-complexity"><span class="header-section-number">10.7.4</span> Oracle Complexity</a></li>
  </ul></li>
  <li><a href="#sec-step-by-step" id="toc-sec-step-by-step" class="nav-link" data-scroll-target="#sec-step-by-step"><span class="header-section-number">10.8</span> Simplex Method Step by Step</a></li>
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary"><span class="header-section-number">10.9</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../lectures/09-lp-formulation-geometry.html">Linear Programming</a></li><li class="breadcrumb-item"><a href="../lectures/10-simplex-method.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Simplex Method</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Simplex Method</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The simplex method is the most celebrated algorithm for solving linear programs. In the <a href="../lectures/09-lp-formulation-geometry.html">previous chapter</a>, the Algebraic Fundamental Theorem of LP revealed that vertices of the feasible polyhedron are exactly the basic feasible solutions (BFS), and that if an optimal solution exists, it can be found at a BFS. This transforms the LP from a continuous optimization problem into a combinatorial search over at most <span class="math inline">\binom{n+m}{m}</span> candidates. Rather than enumerating all of them, the simplex method <em>smartly navigates</em> from one BFS to an adjacent one, improving the objective at every step. Each move is called a <strong>pivot</strong>, and the algorithm terminates when no further improvement is possible, certifying optimality.</p>
<p>In this chapter we develop the full simplex algorithm from scratch. We begin by deriving the method from first principles: starting at a BFS, we use the algebra of the equational form to discover <strong>reduced costs</strong> (which tell us whether the current solution is optimal), the <strong>pivot mechanism</strong> (how to move to a better neighboring BFS), and the conditions for <strong>unboundedness</strong>. We then introduce the <strong>simplex tableau</strong> as a compact bookkeeping device that organizes these quantities for efficient computation. We assemble these pieces into the complete <strong>five-step simplex algorithm</strong>, illustrate it on a worked numerical example, and address the critical question of <strong>initialization</strong> – how to find a starting BFS when one is not immediately available. Finally, we discuss <strong>pivoting rules</strong> (Dantzig’s rule and Bland’s rule), the phenomenon of <strong>degeneracy</strong> and cycling, and the <strong>oracle complexity</strong> of the simplex method.</p>
<section id="what-will-be-covered" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="what-will-be-covered">What Will Be Covered</h2>
<p>This chapter builds the simplex algorithm piece by piece, from first-principles derivation to practical pivoting strategies:</p>
<ul>
<li>Deriving the simplex method: reduced costs, optimality condition, and the pivot mechanism</li>
<li>The simplex tableau: a compact bookkeeping device for efficient implementation</li>
<li>The full five-step simplex algorithm in tableau form</li>
<li>A detailed worked example tracing the simplex method through multiple iterations</li>
<li>Initialization via the Auxiliary LP (Aux-LP)</li>
<li>Pivoting rules: Dantzig’s rule and Bland’s rule</li>
<li>Degeneracy, cycling, and the guarantee of termination</li>
<li>Oracle complexity of the simplex method</li>
</ul>
<div id="fig-simplex-pivot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simplex-pivot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/simplex-pivot.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;10.1: The simplex method traverses vertices of the feasible polytope, improving the objective at each pivot step."><img src="figures/simplex-pivot.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simplex-pivot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: The simplex method traverses vertices of the feasible polytope, improving the objective at each pivot step.
</figcaption>
</figure>
</div>
</section>
<section id="sec-equational-form" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-equational-form"><span class="header-section-number">10.1</span> From Canonical to Equational Form</h2>
<p>Recall from the <a href="../lectures/09-lp-formulation-geometry.html">previous chapter</a> that a linear program in <strong>canonical form</strong> is:</p>
<p><span class="math display">\min \sum_{j=1}^{n} c_j x_j \quad \text{s.t.} \quad \sum_{j=1}^{n} a_{ij} x_j \leq b_i \;\; \forall\, i \in [m], \quad x_j \geq 0 \;\; \forall\, j \in [n].</span></p>
<p>We convert this to <strong>equational form</strong> by introducing <span class="math inline">m</span> slack variables <span class="math inline">x_{n+1}, \ldots, x_{n+m}</span>:</p>
<p><span class="math display">x_{n+i} = b_i - \sum_{j=1}^{n} a_{ij} x_j \geq 0, \quad \forall\, i \in [m].</span></p>
<p>The equational form LP is then:</p>
<p><span class="math display">\min \; c^\top x \quad \text{s.t.} \quad Ax = b, \;\; x \geq 0, \;\; x \in \mathbb{R}^{n+m},</span></p>
<p>where the cost vector, constraint matrix, and right-hand side are:</p>
<p><span class="math display">c = \begin{pmatrix} c_1 \\ \vdots \\ c_n \\ 0 \\ \vdots \\ 0 \end{pmatrix} \in \mathbb{R}^{n+m}, \quad A = \begin{pmatrix} a_{11} &amp; \cdots &amp; a_{1n} &amp; 1 &amp; 0 &amp; \cdots &amp; 0 \\ \vdots &amp; &amp; \vdots &amp; 0 &amp; 1 &amp; \cdots &amp; 0 \\ a_{m1} &amp; \cdots &amp; a_{mn} &amp; 0 &amp; 0 &amp; \cdots &amp; 1 \end{pmatrix} \in \mathbb{R}^{m \times (n+m)}.</span></p>
<p>The <span class="math inline">m</span> columns corresponding to slack variables form an identity matrix, which will play a crucial role in initialization.</p>
</section>
<section id="sec-derivation" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="sec-derivation"><span class="header-section-number">10.2</span> Deriving the Simplex Method</h2>
<p>Before introducing the simplex tableau (a compact bookkeeping device), let us derive the simplex method from first principles. The key idea is simple: <strong>start at a BFS and move to a neighboring BFS with a lower objective value, repeating until no improvement is possible.</strong></p>
<section id="sec-setup" class="level3" data-number="10.2.1">
<h3 data-number="10.2.1" class="anchored" data-anchor-id="sec-setup"><span class="header-section-number">10.2.1</span> Setup and Notation</h3>
<p>Let <span class="math inline">B</span> and <span class="math inline">N</span> denote the sets of <strong>basic</strong> and <strong>non-basic</strong> variable indices, respectively, with <span class="math inline">|B| = m</span>. We partition:</p>
<p><span class="math display">A = \begin{pmatrix} A_B &amp; A_N \end{pmatrix}, \qquad x = \begin{pmatrix} x_B \\ x_N \end{pmatrix}, \qquad c = \begin{pmatrix} c_B \\ c_N \end{pmatrix}.</span></p>
<p>The LP becomes:</p>
<p><span id="eq-simplex-lp"><span class="math display">\min \; z = c_B^\top x_B + c_N^\top x_N \quad \text{s.t.} \quad A_B x_B + A_N x_N = b, \;\; x_B \geq 0, \; x_N \geq 0. \tag{10.1}</span></span></p>
</section>
<section id="sec-starting-bfs" class="level3" data-number="10.2.2">
<h3 data-number="10.2.2" class="anchored" data-anchor-id="sec-starting-bfs"><span class="header-section-number">10.2.2</span> Starting from a BFS</h3>
<p>Assume that the current basis <span class="math inline">B</span> gives a BFS. That is, <span class="math inline">x_B^* = A_B^{-1}b \geq 0</span> and <span class="math inline">x_N^* = 0</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Initial BFS When <span class="math inline">b \geq 0</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">b \geq 0</span>, an initial BFS is immediate: set <span class="math inline">B = \{n+1, n+2, \ldots, n+m\}</span> (the slack variables). Then <span class="math inline">A_B = I_m</span>, so <span class="math inline">x_B^* = b \geq 0</span>, and the original variables <span class="math inline">x_1 = x_2 = \cdots = x_n = 0</span>. When <span class="math inline">b \not\geq 0</span>, finding an initial BFS is itself nontrivial – we address this in <a href="#sec-initialization" class="quarto-xref"><span>Section 10.6</span></a>.</p>
</div>
</div>
<p>Since <span class="math inline">A_B</span> is invertible, we can express the basic variables in terms of the non-basic ones:</p>
<p><span id="eq-basic-from-nonbasic"><span class="math display">x_B = A_B^{-1}b - A_B^{-1}A_N x_N = x_B^* - A_B^{-1}A_N x_N. \tag{10.2}</span></span></p>
<p>This is the key equation: it tells us exactly how the basic variables respond when we perturb the non-basic variables away from zero.</p>
</section>
<section id="sec-reduced-costs" class="level3" data-number="10.2.3">
<h3 data-number="10.2.3" class="anchored" data-anchor-id="sec-reduced-costs"><span class="header-section-number">10.2.3</span> Reduced Costs</h3>
<p>Substituting <a href="#eq-basic-from-nonbasic" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> into the objective of <a href="#eq-simplex-lp" class="quarto-xref">Equation&nbsp;<span>10.1</span></a>:</p>
<p><span class="math display">z = c_B^\top(x_B^* - A_B^{-1}A_N x_N) + c_N^\top x_N = c_B^\top x_B^* + \left(c_N - (A_B^{-1}A_N)^\top c_B\right)^\top x_N.</span></p>
<p>The coefficient of <span class="math inline">x_N</span> in this expression is so important that it gets its own name.</p>
<div id="def-reduced-cost" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.1 (Definition (Reduced Cost Vector))</strong></span> The <strong>reduced cost vector</strong> for the non-basic variables is</p>
<p><span class="math display">r_N = c_N - (A_B^{-1}A_N)^\top c_B = c_N - A_N^\top (A_B^{-1})^\top c_B \;\in \mathbb{R}^n.</span></p>
<p>The <span class="math inline">j</span>-th component <span class="math inline">r_j</span> (for <span class="math inline">j \in N</span>) represents the <strong>rate of change of the objective</strong> when <span class="math inline">x_j</span> increases from zero, holding other non-basic variables at zero.</p>
</div>
<p>The objective can thus be written as:</p>
<p><span id="eq-objective-reduced"><span class="math display">z = \underbrace{c_B^\top A_B^{-1} b}_{z^* \text{ (current value)}} + r_N^\top x_N. \tag{10.3}</span></span></p>
<p>Since <span class="math inline">x_N = 0</span> at the current BFS, the current objective value is <span class="math inline">z^* = c_B^\top A_B^{-1}b</span>.</p>
</section>
<section id="sec-optimality" class="level3" data-number="10.2.4">
<h3 data-number="10.2.4" class="anchored" data-anchor-id="sec-optimality"><span class="header-section-number">10.2.4</span> Optimality Condition</h3>
<p>From <a href="#eq-objective-reduced" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>, we can read off the optimality condition immediately.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Optimality Condition
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">r_N \geq 0</span> (all reduced costs are nonneg), the current BFS is <strong>optimal</strong>. <strong>STOP.</strong></p>
<p><strong>Why?</strong> Since <span class="math inline">x_N \geq 0</span> (feasibility) and <span class="math inline">r_N \geq 0</span>, we have <span class="math inline">z = z^* + r_N^\top x_N \geq z^*</span> for every feasible point. The current BFS achieves the minimum.</p>
</div>
</div>
</section>
<section id="sec-pivot-mechanism" class="level3" data-number="10.2.5">
<h3 data-number="10.2.5" class="anchored" data-anchor-id="sec-pivot-mechanism"><span class="header-section-number">10.2.5</span> The Pivot Mechanism</h3>
<p>This is the heart of the simplex method. The reduced cost equation <a href="#eq-objective-reduced" class="quarto-xref">Equation&nbsp;<span>10.3</span></a> tells us <span class="math inline">z = z^* + r_N^\top x_N</span>, and we want to decrease <span class="math inline">z</span>. Currently all non-basic variables are zero. The entire strategy reduces to two questions.</p>
<section id="question-1-which-non-basic-variable-should-we-increase" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-1-which-non-basic-variable-should-we-increase">Question 1: Which non-basic variable should we increase?</h4>
<p>Scan the reduced cost vector <span class="math inline">r_N</span>. If some component <span class="math inline">r_q &lt; 0</span>, then increasing <span class="math inline">x_q</span> from zero will decrease the objective (since the contribution is <span class="math inline">r_q \cdot x_q &lt; 0</span>). We select such a <span class="math inline">q</span> as the <strong>entering variable</strong>.</p>
<p>If no such <span class="math inline">q</span> exists – that is, <span class="math inline">r_N \geq 0</span> – then increasing <em>any</em> non-basic variable can only increase or maintain the objective. <strong>We are already at the optimum.</strong> This is the optimality condition from <a href="#sec-optimality" class="quarto-xref"><span>Section 10.2.4</span></a>.</p>
</section>
<section id="question-2-how-far-can-we-increase-x_q" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="question-2-how-far-can-we-increase-x_q">Question 2: How far can we increase <span class="math inline">x_q</span>?</h4>
<p>We want to push <span class="math inline">x_q</span> as large as possible (to decrease <span class="math inline">z</span> as much as possible), but we must maintain feasibility: all basic variables must stay nonneg. Setting <span class="math inline">x_q = t &gt; 0</span> and keeping all other non-basic variables at zero, <a href="#eq-basic-from-nonbasic" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> gives:</p>
<p><span class="math display">x_B = x_B^* - t \cdot d_q, \qquad \text{where } d_q = A_B^{-1} a_q \in \mathbb{R}^m</span></p>
<p>is the <strong>pivot column</strong> (<span class="math inline">a_q</span> is the <span class="math inline">q</span>-th column of <span class="math inline">A</span>). The <span class="math inline">i</span>-th entry <span class="math inline">d_{iq}</span> tells us how much basic variable <span class="math inline">x_i</span> decreases when <span class="math inline">x_q</span> increases by one unit.</p>
<p>The feasibility requirement <span class="math inline">x_B \geq 0</span> – i.e., <span class="math inline">x_i^* - t \cdot d_{iq} \geq 0</span> for all <span class="math inline">i \in B</span> – determines how far we can go:</p>
<ul>
<li><p><strong>If <span class="math inline">d_{iq} \leq 0</span> for all <span class="math inline">i \in B</span>:</strong> No basic variable decreases when <span class="math inline">x_q</span> grows. We can push <span class="math inline">t \to \infty</span>, and the objective <span class="math inline">z = z^* + r_q \cdot t \to -\infty</span>. The LP is <strong>unbounded</strong>.</p></li>
<li><p><strong>If some <span class="math inline">d_{iq} &gt; 0</span>:</strong> These basic variables <em>do</em> decrease as <span class="math inline">x_q</span> grows. The tightest constraint determines the maximum step:</p></li>
</ul>
<p><span class="math display">t^* = \min_{i \in B : d_{iq} &gt; 0} \frac{x_i^*}{d_{iq}}.</span></p>
<p>The basic variable that hits zero first is the <strong>leaving variable</strong> – it exits the basis to make room for <span class="math inline">x_q</span>:</p>
<p><span class="math display">p = \arg\min_{i \in B : d_{iq} &gt; 0} \frac{x_i^*}{d_{iq}}.</span></p>
</section>
<section id="the-pivot" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="the-pivot">The Pivot</h4>
<p>We swap <span class="math inline">q</span> into the basis and <span class="math inline">p</span> out:</p>
<p><span class="math display">B' = B \cup \{q\} \setminus \{p\}, \qquad N' = N \cup \{p\} \setminus \{q\}.</span></p>
<p>The new BFS has <span class="math inline">x_q = t^* &gt; 0</span>, <span class="math inline">x_p = 0</span>, and the objective has strictly decreased:</p>
<p><span class="math display">z_{\text{new}} = z^* + r_q \cdot t^* &lt; z^* \quad (\text{since } r_q &lt; 0 \text{ and } t^* &gt; 0).</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Summary of the Pivot Logic
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\boxed{r_q &lt; 0 \text{ ?}} \;\xrightarrow{\;\text{yes}\;}\; \boxed{\text{increase } x_q} \;\xrightarrow{\;x_i^* = 0\;}\; \boxed{\text{swap } q \leftrightarrow p} \;\rightarrow\; \text{better BFS}</span></p>
<ul>
<li>No <span class="math inline">r_q &lt; 0</span> exists <span class="math inline">\;\Rightarrow\;</span> <strong>optimal</strong> (stop).</li>
<li>No basic variable blocks the increase <span class="math inline">\;\Rightarrow\;</span> <strong>unbounded</strong> (stop).</li>
</ul>
</div>
</div>
</section>
</section>
<section id="sec-simplex-algorithm" class="level3" data-number="10.2.6">
<h3 data-number="10.2.6" class="anchored" data-anchor-id="sec-simplex-algorithm"><span class="header-section-number">10.2.6</span> The Simplex Algorithm</h3>
<p>Putting it all together:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The Simplex Method
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Input:</strong> An initial BFS with basis <span class="math inline">B</span>, <span class="math inline">x_B^* = A_B^{-1}b \geq 0</span>.</p>
<p><strong>Repeat:</strong></p>
<ol type="1">
<li><p><strong>Compute reduced costs:</strong> <span class="math inline">r_N = c_N - A_N^\top (A_B^{-1})^\top c_B</span>.</p></li>
<li><p><strong>Optimality test:</strong> If <span class="math inline">r_N \geq 0</span>, <strong>STOP</strong> – the current BFS is optimal.</p></li>
<li><p><strong>Select entering variable:</strong> Choose <span class="math inline">q \in N</span> with <span class="math inline">r_q &lt; 0</span>.</p></li>
<li><p><strong>Compute pivot column:</strong> <span class="math inline">d_q = A_B^{-1} a_q</span>.</p></li>
<li><p><strong>Unboundedness test:</strong> If <span class="math inline">d_q \leq 0</span>, <strong>STOP</strong> – the LP is unbounded.</p></li>
<li><p><strong>Compute step size and leaving variable:</strong></p></li>
</ol>
<p><span class="math display">t^* = \min_{i \in B : d_{iq} &gt; 0} \frac{x_i^*}{d_{iq}}, \qquad p = \arg\min_{i \in B : d_{iq} &gt; 0} \frac{x_i^*}{d_{iq}}.</span></p>
<ol start="7" type="1">
<li><strong>Pivot:</strong> Update <span class="math inline">B \leftarrow B \cup \{q\} \setminus \{p\}</span>, <span class="math inline">N \leftarrow N \cup \{p\} \setminus \{q\}</span>. Recompute <span class="math inline">x_B^* = A_B^{-1}b</span>.</li>
</ol>
</div>
</div>
<p>Each iteration moves from one BFS to an <strong>adjacent</strong> BFS (one that differs by exactly one basic variable) while strictly decreasing the objective (assuming nondegeneracy). Since there are finitely many BFS, the algorithm terminates.</p>
</section>
<section id="sec-why-simplex" class="level3" data-number="10.2.7">
<h3 data-number="10.2.7" class="anchored" data-anchor-id="sec-why-simplex"><span class="header-section-number">10.2.7</span> Why the Simplex Method Works</h3>
<p>The correctness of the simplex method rests on three pillars:</p>
<ol type="1">
<li><p><strong>Finiteness of BFS.</strong> There are at most <span class="math inline">\binom{n+m}{m}</span> basic feasible solutions. If each pivot strictly decreases the objective (which happens when the LP is nondegenerate), the algorithm cannot revisit a BFS and must terminate.</p></li>
<li><p><strong>Optimality certificate.</strong> When <span class="math inline">r_N \geq 0</span>, the current BFS is provably optimal: <a href="#eq-objective-reduced" class="quarto-xref">Equation&nbsp;<span>10.3</span></a> shows that <span class="math inline">z = z^* + r_N^\top x_N \geq z^*</span> for all feasible <span class="math inline">x_N \geq 0</span>.</p></li>
<li><p><strong>Unboundedness detection.</strong> When <span class="math inline">d_q \leq 0</span> for some <span class="math inline">q</span> with <span class="math inline">r_q &lt; 0</span>, we can construct a feasible ray along which the objective decreases without bound.</p></li>
</ol>
</section>
</section>
<section id="sec-tableau" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-tableau"><span class="header-section-number">10.3</span> The Simplex Tableau</h2>
<p>The derivation in <a href="12-dual-simplex.html#sec-derivation" class="quarto-xref"><span>Section 12.4</span></a> gives us everything we need to run the simplex method. But look at what each iteration requires: computing <span class="math inline">A_B^{-1}b</span>, <span class="math inline">A_B^{-1}A_N</span>, and <span class="math inline">r_N</span> – all involving <span class="math inline">A_B^{-1}</span>, which changes at every pivot. Rather than recomputing these from scratch, we organize them into a single data structure – the <strong>simplex tableau</strong> – that can be updated cheaply after each pivot.</p>
<section id="sec-tableau-setup" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="sec-tableau-setup"><span class="header-section-number">10.3.1</span> Tableau Quantities</h3>
<p>In <a href="#sec-reduced-costs" class="quarto-xref"><span>Section 10.2.3</span></a> we derived two key equations. The <strong>constraint equation</strong> (<a href="#eq-basic-from-nonbasic" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>):</p>
<p><span class="math display">x_B = \underbrace{A_B^{-1}b}_{\text{current BFS}} - \underbrace{A_B^{-1}A_N}_{\text{exchange rates}} \, x_N,</span></p>
<p>and the <strong>objective equation</strong> (<a href="#eq-objective-reduced" class="quarto-xref">Equation&nbsp;<span>10.3</span></a>):</p>
<p><span class="math display">z = \underbrace{c_B^\top A_B^{-1}b}_{\text{current value}} + \underbrace{r_N^\top}_{\text{reduced costs}} x_N.</span></p>
<p>The simplex tableau collects these quantities under a compact notation.</p>
<div id="def-simplex-quantities" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.2 (Simplex Tableau Quantities)</strong></span> Given a basis <span class="math inline">B</span> with BFS <span class="math inline">x_B^* = A_B^{-1} b \geq 0</span>, define:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 19%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Definition</th>
<th>Meaning</th>
<th>Role in derivation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\widetilde{b}</span></td>
<td><span class="math inline">A_B^{-1} b</span></td>
<td>Current BFS values</td>
<td><span class="math inline">x_B^*</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\widetilde{A}</span></td>
<td><span class="math inline">A_B^{-1} A_N</span></td>
<td>How basic variables respond to non-basic ones</td>
<td>Exchange coefficients in <a href="#eq-basic-from-nonbasic" class="quarto-xref">Equation&nbsp;<span>10.2</span></a></td>
</tr>
<tr class="odd">
<td><span class="math inline">\widetilde{c}</span></td>
<td><span class="math inline">c_N - \widetilde{A}^\top c_B</span></td>
<td>Cost of increasing each non-basic variable</td>
<td>Reduced costs <span class="math inline">r_N</span> from <a href="#def-reduced-cost" class="quarto-xref">Definition&nbsp;<span>10.1</span></a></td>
</tr>
<tr class="even">
<td><span class="math inline">\widetilde{\zeta}</span></td>
<td><span class="math inline">c_B^\top \widetilde{b}</span></td>
<td>Current objective value</td>
<td><span class="math inline">z^*</span> from <a href="#eq-objective-reduced" class="quarto-xref">Equation&nbsp;<span>10.3</span></a></td>
</tr>
</tbody>
</table>
</div>
<p>The tilde notation is simply shorthand: <span class="math inline">\widetilde{c}</span> is the reduced cost vector <span class="math inline">r_N</span>, <span class="math inline">\widetilde{b}</span> is the current BFS <span class="math inline">x_B^*</span>, and <span class="math inline">\widetilde{A}</span> is the matrix that tells us how the basic variables change when the non-basic variables move away from zero.</p>
</section>
<section id="sec-dictionary" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="sec-dictionary"><span class="header-section-number">10.3.2</span> The Dictionary Form</h3>
<p>Substituting the tableau quantities, the two key equations become:</p>
<p><span class="math display">\zeta = \widetilde{\zeta} + \widetilde{c}^\top x_N, \qquad x_B = \widetilde{b} - \widetilde{A}\, x_N.</span></p>
<p>Together, these give the LP in <strong>dictionary form</strong>:</p>
<p><span id="eq-dictionary-form"><span class="math display">\min_{x_N} \; \zeta = \widetilde{\zeta} + \widetilde{c}^\top x_N \quad \text{s.t.} \quad x_B = \widetilde{b} - \widetilde{A}\, x_N, \;\; x_B, x_N \geq 0. \tag{10.4}</span></span></p>
<p>This is equivalent to the original LP, but expressed entirely in terms of the non-basic variables <span class="math inline">x_N</span>. At the current BFS, <span class="math inline">x_N = 0</span>, so <span class="math inline">x_B = \widetilde{b}</span> and <span class="math inline">\zeta = \widetilde{\zeta}</span>. The dictionary makes the pivot logic transparent: to improve the objective, find a non-basic variable with <span class="math inline">\widetilde{c}_q &lt; 0</span> and increase it until some basic variable hits zero.</p>
</section>
<section id="sec-tableau-layout" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="sec-tableau-layout"><span class="header-section-number">10.3.3</span> The Tableau Layout</h3>
<p>The dictionary can be written as a single matrix equation:</p>
<p><span id="eq-tableau-form"><span class="math display">\begin{pmatrix} \zeta \\ x_B \end{pmatrix} = \begin{pmatrix} \widetilde{\zeta} &amp; \widetilde{c}^\top \\ \widetilde{b} &amp; -\widetilde{A} \end{pmatrix} \begin{pmatrix} 1 \\ x_N \end{pmatrix}. \tag{10.5}</span></span></p>
<p>The matrix on the right is the <strong>simplex tableau</strong>:</p>
<p><span class="math display">\text{Tableau} = \begin{pmatrix} \widetilde{\zeta} &amp; \widetilde{c}^\top \\ \hline \widetilde{b} &amp; -\widetilde{A} \end{pmatrix}.</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reading the Tableau
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Top-left entry</strong> <span class="math inline">\widetilde{\zeta}</span>: current objective value.</li>
<li><strong>Top row</strong> <span class="math inline">\widetilde{c}^\top</span>: reduced costs of non-basic variables. Negative entries signal room for improvement.</li>
<li><strong>Left column</strong> <span class="math inline">\widetilde{b}</span>: current values of basic variables (the BFS).</li>
<li><strong>Body</strong> <span class="math inline">-\widetilde{A}</span>: exchange coefficients – column <span class="math inline">q</span> tells you how <span class="math inline">x_B</span> changes when <span class="math inline">x_q</span> increases.</li>
<li><strong>Optimality test:</strong> If <span class="math inline">\widetilde{c} \geq 0</span>, the current BFS is optimal.</li>
<li><strong>Pivoting:</strong> Choose a column <span class="math inline">q</span> with <span class="math inline">\widetilde{c}_q &lt; 0</span> (entering) and a row <span class="math inline">p</span> via the ratio test (leaving), then swap.</li>
</ul>
</div>
</div>
</section>
<section id="sec-pivoting" class="level3" data-number="10.3.4">
<h3 data-number="10.3.4" class="anchored" data-anchor-id="sec-pivoting"><span class="header-section-number">10.3.4</span> Pivoting in Tableau Notation</h3>
<p>The pivot mechanism from <a href="#sec-pivot-mechanism" class="quarto-xref"><span>Section 10.2.5</span></a> translates directly into tableau language. In terms of the tableau quantities:</p>
<ul>
<li><p><strong>Entering variable:</strong> Choose <span class="math inline">q \in N</span> with <span class="math inline">\widetilde{c}_q &lt; 0</span>. The pivot column is <span class="math inline">\widetilde{A}_q</span> (column <span class="math inline">q</span> of <span class="math inline">\widetilde{A}</span>), which plays the role of <span class="math inline">d_q = A_B^{-1}a_q</span> from the derivation.</p></li>
<li><p><strong>Ratio test:</strong> For each row <span class="math inline">i \in B</span> with <span class="math inline">\widetilde{A}_{iq} &gt; 0</span>, compute the ratio <span class="math inline">\widetilde{b}_i / \widetilde{A}_{iq}</span>. The smallest ratio determines the step size and leaving variable:</p></li>
</ul>
<div id="def-ratio-test" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.3 (Ratio Test (Tableau Form))</strong></span> <span id="eq-ratio-test"><span class="math display">t^* = \min\left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0, \;\; i \in B\right\}, \qquad p = \arg\min_{i \in B}\left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0\right\}. \tag{10.6}</span></span></p>
</div>
<ul>
<li><strong>After the pivot:</strong> <span class="math inline">x_p \leftarrow 0</span>, <span class="math inline">x_q \leftarrow t^* = \widetilde{b}_p / \widetilde{A}_{pq}</span>, and the basis updates to <span class="math inline">B' = (B \setminus \{p\}) \cup \{q\}</span>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Properties of a Pivot
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Feasibility is maintained:</strong> The ratio test ensures <span class="math inline">x_B \geq 0</span> after the update.</li>
<li><strong>The objective improves:</strong> The change is <span class="math inline">\Delta\zeta = \widetilde{c}_q \cdot t^* \leq 0</span>, since <span class="math inline">\widetilde{c}_q &lt; 0</span> and <span class="math inline">t^* \geq 0</span>.</li>
<li><strong>Degeneracy warning:</strong> If <span class="math inline">\widetilde{b}_p = 0</span>, then <span class="math inline">t^* = 0</span> and the objective does not decrease. The basis changes, but the BFS point stays put. This is <strong>degeneracy</strong> – we return to it in <a href="#sec-degeneracy" class="quarto-xref"><span>Section 10.7.2</span></a>.</li>
</ol>
</div>
</div>
</section>
</section>
<section id="sec-full-algorithm" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="sec-full-algorithm"><span class="header-section-number">10.4</span> The Full Simplex Algorithm (Tableau Form)</h2>
<p>The simplex method from <a href="#sec-simplex-algorithm" class="quarto-xref"><span>Section 10.2.6</span></a> can now be expressed concisely as a five-step loop over the tableau:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Algorithm: The Simplex Method (5 Steps)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Input:</strong> A basis <span class="math inline">B</span> yielding a BFS <span class="math inline">x_B^* = A_B^{-1} b \geq 0</span>.</p>
<p><strong>Step 1 (Compute tableau):</strong> Compute <span class="math inline">\widetilde{c}</span>, <span class="math inline">\widetilde{A}</span>, <span class="math inline">\widetilde{b}</span>, <span class="math inline">\widetilde{\zeta}</span> from the current basis <span class="math inline">B</span>.</p>
<p><strong>Step 2 (Optimality check):</strong> If <span class="math inline">\widetilde{c}_j \geq 0</span> for all <span class="math inline">j \in N</span>, <strong>STOP</strong> – the current BFS is <strong>optimal</strong>.</p>
<p><strong>Step 3 (Select entering variable):</strong> Choose <span class="math inline">q \in N</span> with <span class="math inline">\widetilde{c}_q &lt; 0</span> (according to some pivoting rule).</p>
<p><strong>Step 4 (Ratio test):</strong> If <span class="math inline">\widetilde{A}_{iq} \leq 0</span> for all <span class="math inline">i \in B</span>, <strong>STOP</strong> – the LP is <strong>unbounded</strong>. Otherwise, compute:</p>
<p><span class="math display">t^* = \min_{i \in B}\left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0\right\}, \quad p = \arg\min_{i \in B}\left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0\right\}.</span></p>
<p><strong>Step 5 (Pivot):</strong> Update <span class="math inline">B \leftarrow (B \setminus \{p\}) \cup \{q\}</span>, <span class="math inline">N \leftarrow (N \setminus \{q\}) \cup \{p\}</span>. Go to Step 1.</p>
</div>
</div>
<div id="fig-simplex-flowchart" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simplex-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/simplex-flowchart.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;10.2: Flowchart of the simplex method. The algorithm iterates through tableau computation, optimality check, entering variable selection, ratio test, and pivoting."><img src="figures/simplex-flowchart.svg" class="img-fluid figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simplex-flowchart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: Flowchart of the simplex method. The algorithm iterates through tableau computation, optimality check, entering variable selection, ratio test, and pivoting.
</figcaption>
</figure>
</div>
<p>The five-step algorithm above is the complete specification of the simplex method. To make the mechanics concrete, we now work through a small example by hand, tracing every tableau computation and pivot decision.</p>
</section>
<section id="sec-example" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-example"><span class="header-section-number">10.5</span> Worked Example</h2>
<p>Let us trace the simplex method on a concrete LP with <span class="math inline">n = 2</span> decision variables and <span class="math inline">m = 2</span> constraints.</p>
<div id="exm-simplex-worked" class="theorem example">
<p><span class="theorem-title"><strong>Example 10.1 (Simplex Method on a 2D LP)</strong></span> Consider the LP in canonical form:</p>
<p><span class="math display">\min \; -x_2 \quad \text{s.t.} \quad -x_1 + x_2 \leq 1, \;\; x_1 + x_2 \leq 2, \;\; x_1, x_2 \geq 0.</span></p>
<p><strong>Equational form.</strong> Introduce slack variables <span class="math inline">x_3, x_4</span>:</p>
<p><span class="math display">\min \; -\bar{c}^\top x \quad \text{s.t.} \quad \bar{A} x = b, \;\; x \geq 0, \;\; x \in \mathbb{R}^4,</span></p>
<p>where</p>
<p><span class="math display">\bar{c} = \begin{pmatrix} 0 \\ -1 \\ 0 \\ 0 \end{pmatrix}, \quad \bar{A} = \begin{pmatrix} -1 &amp; 1 &amp; 1 &amp; 0 \\ 1 &amp; 1 &amp; 0 &amp; 1 \end{pmatrix}, \quad b = \begin{pmatrix} 1 \\ 2 \end{pmatrix}.</span></p>
<p><strong>Enumerate all BFS.</strong> The index set is <span class="math inline">\{1, 2, 3, 4\}</span>. We choose <span class="math inline">m = 2</span> indices for <span class="math inline">B</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 32%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">B</span></th>
<th><span class="math inline">A_B</span></th>
<th><span class="math inline">x_B^* = A_B^{-1}b</span></th>
<th>Full <span class="math inline">x</span></th>
<th>Feasible?</th>
<th>BFS label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\{1,2\}</span></td>
<td><span class="math inline">\begin{pmatrix} -1 &amp; 1 \\ 1 &amp; 1 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} 0.5 \\ 1.5 \end{pmatrix}</span></td>
<td><span class="math inline">(0.5, 1.5, 0, 0)</span></td>
<td>Yes</td>
<td><span class="math inline">a</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\{1,3\}</span></td>
<td><span class="math inline">\begin{pmatrix} -1 &amp; 1 \\ 1 &amp; 0 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} 2 \\ 3 \end{pmatrix}</span></td>
<td><span class="math inline">(2, 0, 3, 0)</span></td>
<td>Yes</td>
<td><span class="math inline">b</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\{1,4\}</span></td>
<td><span class="math inline">\begin{pmatrix} -1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} -1 \\ 3 \end{pmatrix}</span></td>
<td><span class="math inline">(-1, 0, 0, 3)</span></td>
<td><strong>No</strong></td>
<td>–</td>
</tr>
<tr class="even">
<td><span class="math inline">\{2,3\}</span></td>
<td><span class="math inline">\begin{pmatrix} 1 &amp; 1 \\ 1 &amp; 0 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} 2 \\ -1 \end{pmatrix}</span></td>
<td><span class="math inline">(0, 2, -1, 0)</span></td>
<td><strong>No</strong></td>
<td>–</td>
</tr>
<tr class="odd">
<td><span class="math inline">\{2,4\}</span></td>
<td><span class="math inline">\begin{pmatrix} 1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} 1 \\ 1 \end{pmatrix}</span></td>
<td><span class="math inline">(0, 1, 0, 1)</span></td>
<td>Yes</td>
<td><span class="math inline">d</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\{3,4\}</span></td>
<td><span class="math inline">\begin{pmatrix} 1 &amp; 0 \\ 0 &amp; 1 \end{pmatrix}</span></td>
<td><span class="math inline">\begin{pmatrix} 1 \\ 2 \end{pmatrix}</span></td>
<td><span class="math inline">(0, 0, 1, 2)</span></td>
<td>Yes</td>
<td><span class="math inline">e</span></td>
</tr>
</tbody>
</table>
<p>There are 4 feasible BFS: <span class="math inline">a, b, d, e</span>.</p>
<p><strong>Simplex iterations.</strong> We initialize with <span class="math inline">B = \{3, 4\}</span> (the slack variables), which gives the BFS <span class="math inline">e = (0, 0, 1, 2)</span> at the origin.</p>
<p><strong>Initialization.</strong> <span class="math inline">B = \{3, 4\}</span>, <span class="math inline">N = \{1, 2\}</span>.</p>
<p>Compute the tableau quantities:</p>
<p><span class="math display">\widetilde{A} = A_B^{-1} A_N = I \cdot \begin{pmatrix} -1 &amp; 1 \\ 1 &amp; 1 \end{pmatrix} = \begin{pmatrix} -1 &amp; 1 \\ 1 &amp; 1 \end{pmatrix}, \quad \widetilde{b} = \begin{pmatrix} 1 \\ 2 \end{pmatrix}, \quad \widetilde{c} = c_N - \widetilde{A}^\top c_B = \begin{pmatrix} 0 \\ -1 \end{pmatrix} - \begin{pmatrix} 0 \\ 0 \end{pmatrix} = \begin{pmatrix} 0 \\ -1 \end{pmatrix}.</span></p>
<p>Since <span class="math inline">\widetilde{c}_2 = -1 &lt; 0</span>, the BFS is not optimal. We choose <span class="math inline">q = 2</span> (entering variable).</p>
<p><strong>Ratio test:</strong> We need <span class="math inline">t \cdot \widetilde{A}_{iq} \leq \widetilde{b}_i</span> for each <span class="math inline">i</span> with <span class="math inline">\widetilde{A}_{iq} &gt; 0</span>:</p>
<p><span class="math display">t \cdot \begin{pmatrix} 1 \\ 1 \end{pmatrix} \leq \begin{pmatrix} 1 \\ 2 \end{pmatrix} \quad \Longrightarrow \quad t^* = \min\left\{\frac{1}{1}, \frac{2}{1}\right\} = 1, \quad p = 3.</span></p>
<p><strong>Iteration 1.</strong> Pivot <span class="math inline">(p, q) = (3, 2)</span>. Update <span class="math inline">B = \{2, 4\}</span>, <span class="math inline">N = \{1, 3\}</span>.</p>
<p>Compute the new tableau:</p>
<p><span class="math display">\widetilde{A} = A_B^{-1} A_N = \begin{pmatrix} 1 &amp; 0 \\ 1 &amp; 1 \end{pmatrix}^{-1}\begin{pmatrix} -1 &amp; 1 \\ 1 &amp; 0 \end{pmatrix} = \begin{pmatrix} -1 &amp; 1 \\ 2 &amp; -1 \end{pmatrix}, \quad \widetilde{b} = \begin{pmatrix} 1 \\ 1 \end{pmatrix}, \quad \widetilde{c} = \begin{pmatrix} -1 \\ 1 \end{pmatrix}.</span></p>
<p>Note: <span class="math inline">\widetilde{c}_1 = -1 &lt; 0</span>, so choose <span class="math inline">q = 1</span> (entering variable).</p>
<p><strong>Ratio test:</strong></p>
<p><span class="math display">t \cdot \begin{pmatrix} -1 \\ 2 \end{pmatrix} \leq \begin{pmatrix} 1 \\ 1 \end{pmatrix}.</span></p>
<p>Only <span class="math inline">\widetilde{A}_{2,1} = 2 &gt; 0</span> (the row for index 4), so <span class="math inline">t^* = 1/2</span>, <span class="math inline">p = 4</span>. Pivot <span class="math inline">(4, 1)</span>.</p>
<p><strong>Iteration 2.</strong> Pivot <span class="math inline">(p, q) = (4, 1)</span>. Update <span class="math inline">B = \{1, 2\}</span>, <span class="math inline">N = \{3, 4\}</span>.</p>
<p>This gives BFS <span class="math inline">a = (0.5, 1.5, 0, 0)</span> with objective <span class="math inline">\zeta = -1.5</span>.</p>
<p>Computing the new relative costs: <span class="math inline">\widetilde{c} \geq 0</span> (both components nonneg). <strong>STOP – optimal!</strong></p>
<p>The simplex method found the optimal solution <span class="math inline">x^* = (0.5, 1.5)</span> with <span class="math inline">\zeta^* = -1.5</span> in two pivots, visiting BFS <span class="math inline">e \to d \to a</span>.</p>
</div>
<div id="fig-simplex-path" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simplex-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/simplex-path.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;10.3: The simplex method traces a path along edges of the feasible polytope. Starting from the origin (BFS e), it pivots to BFS d, then to the optimal BFS a at (0.5, 1.5) with \zeta^* = -1.5."><img src="figures/simplex-path.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simplex-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: The simplex method traces a path along edges of the feasible polytope. Starting from the origin (BFS <span class="math inline">e</span>), it pivots to BFS <span class="math inline">d</span>, then to the optimal BFS <span class="math inline">a</span> at <span class="math inline">(0.5, 1.5)</span> with <span class="math inline">\zeta^* = -1.5</span>.
</figcaption>
</figure>
</div>
<div id="fig-simplex-tableau" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simplex-tableau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/simplex-tableau.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;10.4: The simplex tableau at each iteration. The method starts with basis B=\{3,4\} (slack variables), pivots twice, and terminates at the optimal basis B=\{1,2\} with x^* = (\frac{1}{2}, \frac{3}{2}) and f^* = -\frac{3}{2}. Red entries indicate negative reduced costs that trigger a pivot; green entries confirm optimality."><img src="figures/simplex-tableau.svg" class="img-fluid figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simplex-tableau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.4: The simplex tableau at each iteration. The method starts with basis <span class="math inline">B=\{3,4\}</span> (slack variables), pivots twice, and terminates at the optimal basis <span class="math inline">B=\{1,2\}</span> with <span class="math inline">x^* = (\frac{1}{2}, \frac{3}{2})</span> and <span class="math inline">f^* = -\frac{3}{2}</span>. Red entries indicate negative reduced costs that trigger a pivot; green entries confirm optimality.
</figcaption>
</figure>
</div>
<!-- Remove obsolete interactive tableau -->
<div style="display:none;">
<script>
(function() {
  var iterations = [
    {title: 'Iteration 0: B={3,4}, N={1,2}', B: [3,4], N: [1,2],
     b_tilde: [1,2], A_tilde: [[-1,1],[1,1]], c_tilde: [0,-1], zeta: 0,
     entering: 'q=2 (c\u0303\u2082=\u22121<0)', leaving: 'p=3 (min{1/1, 2/1}=1)',
     status: 'Not optimal: c\u0303\u2082 = \u22121 < 0'},
    {title: 'Iteration 1: B={2,4}, N={1,3}', B: [2,4], N: [1,3],
     b_tilde: [1,1], A_tilde: [[-1,1],[2,-1]], c_tilde: [-1,1], zeta: -1,
     entering: 'q=1 (c\u0303\u2081=\u22121<0)', leaving: 'p=4 (min{\u2014, 1/2}=0.5)',
     status: 'Not optimal: c\u0303\u2081 = \u22121 < 0'},
    {title: 'Iteration 2: B={1,2}, N={3,4}', B: [1,2], N: [3,4],
     b_tilde: [0.5,1.5], A_tilde: [[0.5,-0.5],[0.5,0.5]], c_tilde: [0.5,0.5], zeta: -1.5,
     entering: 'None', leaving: 'None',
     status: 'OPTIMAL: all c\u0303 \u2265 0'}
  ];

  function fmt(v) { return (v >= 0 ? '+' : '') + v.toFixed(1); }

  var allTraces = [];
  for (var k = 0; k < iterations.length; k++) {
    var it = iterations[k];
    var header = ['', 'x<sub>' + it.N[0] + '</sub>', 'x<sub>' + it.N[1] + '</sub>'];
    var col0 = ['\u03b6\u0303 = ' + it.zeta];
    var col1 = [fmt(it.c_tilde[0])];
    var col2 = [fmt(it.c_tilde[1])];
    var fc0 = ['rgba(184,153,94,0.15)'];
    var fc1 = ['rgba(184,153,94,0.15)'];
    var fc2 = ['rgba(184,153,94,0.15)'];
    for (var r = 0; r < it.B.length; r++) {
      col0.push('x<sub>' + it.B[r] + '</sub> = ' + it.b_tilde[r].toFixed(1));
      col1.push(fmt(-it.A_tilde[r][0]));
      col2.push(fmt(-it.A_tilde[r][1]));
      fc0.push('rgba(123,143,163,0.08)');
      fc1.push('rgba(123,143,163,0.08)');
      fc2.push('rgba(123,143,163,0.08)');
    }
    allTraces.push({
      type: 'table',
      header: {values: header, fill: {color: 'rgba(123,143,163,0.25)'},
        font: {size: 13}, align: 'center', height: 30},
      cells: {values: [col0, col1, col2], fill: {color: [fc0, fc1, fc2]},
        font: {size: 13}, align: 'center', height: 28},
      visible: (k === 0)
    });
  }

  var buttons = [];
  for (var k = 0; k < iterations.length; k++) {
    var vis = [false, false, false]; vis[k] = true;
    var it = iterations[k];
    var statusText = '<b>' + it.status + '</b>';
    if (it.entering !== 'None') {
      statusText += '<br>Entering: ' + it.entering + '<br>Leaving: ' + it.leaving;
    }
    buttons.push({label: it.title, method: 'update',
      args: [{visible: vis},
        {annotations: [{x: 0.5, y: -0.15, xref: 'paper', yref: 'paper',
          text: statusText, showarrow: false, font: {size: 12}, align: 'center'}]}]
    });
  }

  var initStatus = '<b>' + iterations[0].status + '</b><br>Entering: ' + iterations[0].entering + '<br>Leaving: ' + iterations[0].leaving;

  var layout = themeLayout({
    updatemenus: [{type: 'dropdown', direction: 'down',
      x: 0.5, xanchor: 'center', y: 1.15, yanchor: 'top',
      buttons: buttons, font: {size: 12}}],
    annotations: [{x: 0.5, y: -0.15, xref: 'paper', yref: 'paper',
      text: initStatus, showarrow: false, font: {size: 12}, align: 'center'}],
    margin: {t: 60, b: 80, l: 20, r: 20}, height: 280
  });

  Plotly.newPlot('fig-tableau-iterations', allTraces, layout, plotlyConfig);
})();
</script>
</div>
<p>The worked example above started from the slack-variable basis <span class="math inline">B = \{3, 4\}</span>, which was immediately feasible because <span class="math inline">b \geq 0</span>. But what happens when some right-hand-side entries are negative and the slack-variable basis is infeasible? We need a systematic method for finding an initial BFS.</p>
</section>
<section id="sec-initialization" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="sec-initialization"><span class="header-section-number">10.6</span> Simplex Initialization via Auxiliary LP</h2>
<p>The simplex method requires a starting BFS. When <span class="math inline">b \geq 0</span>, this is easy: use the slack-variable basis <span class="math inline">B = \{n+1, \ldots, n+m\}</span>, which gives <span class="math inline">x_B^* = b \geq 0</span> (as we noted in <a href="#sec-starting-bfs" class="quarto-xref"><span>Section 10.2.2</span></a>). But what if some <span class="math inline">b_i &lt; 0</span>? Then <span class="math inline">x_B^* = b</span> has negative entries, so the slack-variable basis is <em>infeasible</em>. We cannot simply pick a basis and hope it works – we need a systematic method to either find a feasible BFS or certify that none exists.</p>
<section id="sec-aux-idea" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="sec-aux-idea"><span class="header-section-number">10.6.1</span> The Key Idea</h3>
<p>The idea is beautifully simple: <strong>reduce the feasibility problem to an optimization problem that we already know how to solve.</strong></p>
<p>We introduce an auxiliary variable <span class="math inline">x_0 \geq 0</span> that acts as a “buffer.” We subtract <span class="math inline">x_0</span> from the left-hand side of every constraint:</p>
<p><span class="math display">\sum_{j=1}^{n} a_{ij} x_j - x_0 \leq b_i, \quad \forall\, i \in [m].</span></p>
<p>By making <span class="math inline">x_0</span> large enough, we can satisfy <em>any</em> constraint, even those with <span class="math inline">b_i &lt; 0</span>. The question is: can we shrink <span class="math inline">x_0</span> all the way down to zero while keeping all constraints satisfied? If yes, then with <span class="math inline">x_0 = 0</span> the constraints reduce to the original ones, and we have found a feasible point for the original LP.</p>
<p>This leads to the <strong>Auxiliary LP</strong>: minimize <span class="math inline">x_0</span> subject to the modified constraints.</p>
<div id="def-auxiliary-lp" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.4 (Auxiliary LP)</strong></span> Given the original LP <span class="math inline">\min c^\top x</span> s.t. <span class="math inline">\sum_{j=1}^n a_{ij} x_j \leq b_i</span>, <span class="math inline">x_j \geq 0</span>, the <strong>Auxiliary LP</strong> is:</p>
<p><span class="math display">\text{(Aux-LP)} \quad \min \; x_0 \quad \text{s.t.} \quad \sum_{j=1}^{n} a_{ij} x_j - x_0 \leq b_i \;\; \forall\, i \in [m], \quad x_j \geq 0 \;\; \forall\, j \in \{0, 1, \ldots, n\}.</span></p>
</div>
</section>
<section id="sec-aux-why" class="level3" data-number="10.6.2">
<h3 data-number="10.6.2" class="anchored" data-anchor-id="sec-aux-why"><span class="header-section-number">10.6.2</span> Why This Works</h3>
<p>The Aux-LP has three key properties:</p>
<p><strong>Property 1: The Aux-LP is always feasible (and we can find a starting BFS).</strong></p>
<p>Set <span class="math inline">x_1 = \cdots = x_n = 0</span>. The <span class="math inline">i</span>-th constraint becomes <span class="math inline">-x_0 \leq b_i</span>, i.e., <span class="math inline">x_0 \geq -b_i</span>. Choosing <span class="math inline">x_0 = \max_i(-b_i) = -\min_i b_i &gt; 0</span> satisfies all constraints. After adding slack variables <span class="math inline">s_1, \ldots, s_m</span>, the equational form of the Aux-LP is:</p>
<p><span class="math display">\sum_{j=1}^{n} a_{ij} x_j - x_0 + s_i = b_i, \quad s_i \geq 0.</span></p>
<p>With <span class="math inline">x_j = 0</span> for <span class="math inline">j \geq 1</span> and <span class="math inline">x_0 = -\min_i b_i</span>, the slack values are <span class="math inline">s_i = b_i + x_0</span>. For the row <span class="math inline">k</span> where <span class="math inline">b_k</span> is most negative, <span class="math inline">s_k = 0</span>. This gives an initial BFS with basis <span class="math inline">B = \{x_0, s_1, \ldots, s_m\} \setminus \{s_k\}</span> – we replace the slack <span class="math inline">s_k</span> with <span class="math inline">x_0</span> in the basis.</p>
<p><strong>Property 2: The original LP is feasible <span class="math inline">\iff</span> the optimal value of the Aux-LP is zero.</strong></p>
<ul>
<li>(<span class="math inline">\Rightarrow</span>) If the original LP has a feasible point <span class="math inline">x^*</span>, then <span class="math inline">(x_0, x^*) = (0, x^*)</span> satisfies all Aux-LP constraints (they reduce to the original constraints when <span class="math inline">x_0 = 0</span>). Since <span class="math inline">x_0 \geq 0</span>, the minimum of the Aux-LP is at most 0, hence exactly 0.</li>
<li>(<span class="math inline">\Leftarrow</span>) If the Aux-LP achieves <span class="math inline">x_0^* = 0</span>, the accompanying <span class="math inline">x^*</span> satisfies the original constraints (plug <span class="math inline">x_0 = 0</span> back in).</li>
</ul>
<p><strong>Property 3: The optimal BFS of the Aux-LP provides a starting BFS for the original LP.</strong></p>
<p>When <span class="math inline">x_0^* = 0</span>, the Aux-LP’s optimal BFS consists of values for <span class="math inline">x_1, \ldots, x_n</span> and the slack variables <span class="math inline">s_1, \ldots, s_m</span> that satisfy <span class="math inline">Ax + s = b</span>, <span class="math inline">x, s \geq 0</span>. We need to extract a BFS for the original LP from this.</p>
<ul>
<li><strong>Generic case (<span class="math inline">x_0</span> is non-basic):</strong> Since non-basic variables are zero, <span class="math inline">x_0 = 0</span> is already enforced. The remaining basic variables (a subset of <span class="math inline">x_1, \ldots, x_n, s_1, \ldots, s_m</span>) form a valid BFS for the original equational form. Simply drop <span class="math inline">x_0</span> from the non-basic set.</li>
<li><strong>Degenerate case (<span class="math inline">x_0</span> is basic with value 0):</strong> Here <span class="math inline">x_0</span> sits in the basis at value zero. We must pivot <span class="math inline">x_0</span> out of the basis before proceeding. Choose any non-basic original variable <span class="math inline">x_j</span> (or slack <span class="math inline">s_j</span>) with a nonzero entry in <span class="math inline">x_0</span>’s row, and perform one additional pivot to swap <span class="math inline">x_0</span> out. This pivot does not change the BFS values (since <span class="math inline">x_0 = 0</span>), it merely adjusts which variables are labeled basic vs.&nbsp;non-basic.</li>
</ul>
</section>
<section id="sec-init-algorithm" class="level3" data-number="10.6.3">
<h3 data-number="10.6.3" class="anchored" data-anchor-id="sec-init-algorithm"><span class="header-section-number">10.6.3</span> The Initialization Algorithm</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Algorithm: Simplex Initialization
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Check</strong> if <span class="math inline">b \geq 0</span>. If so, use <span class="math inline">B = \{n+1, \ldots, n+m\}</span> (slack variables) as the initial basis. <strong>Done.</strong></p></li>
<li><p><strong>Formulate the Aux-LP:</strong> Add the buffer variable <span class="math inline">x_0</span> to every constraint. The objective is <span class="math inline">\min x_0</span>.</p></li>
<li><p><strong>Find a starting BFS for the Aux-LP:</strong> Set <span class="math inline">x_j = 0</span> for <span class="math inline">j = 1, \ldots, n</span> and <span class="math inline">x_0 = -\min_i b_i</span>. The row with the most negative <span class="math inline">b_i</span> contributes <span class="math inline">x_0</span> to the basis in place of its slack variable.</p></li>
<li><p><strong>Solve the Aux-LP</strong> using the simplex method.</p></li>
<li><p><strong>Interpret the result:</strong></p>
<ul>
<li>If the optimal value is <strong>zero</strong>: extract the BFS (dropping <span class="math inline">x_0</span>) and use it to initialize simplex on the original LP.</li>
<li>If the optimal value is <strong>positive</strong>: the original LP is <strong>infeasible</strong>.</li>
</ul></li>
</ol>
</div>
</div>
</section>
<section id="sec-aux-example" class="level3" data-number="10.6.4">
<h3 data-number="10.6.4" class="anchored" data-anchor-id="sec-aux-example"><span class="header-section-number">10.6.4</span> Example</h3>
<div id="exm-aux-lp" class="theorem example">
<p><span class="theorem-title"><strong>Example 10.2 (Auxiliary LP Example)</strong></span> Consider the LP:</p>
<p><span class="math display">\min \; -x_1 + x_2 - x_3 \quad \text{s.t.} \quad 2x_1 - x_2 + 2x_3 \leq 4, \;\; 2x_1 - 3x_2 + x_3 \leq -5, \;\; -x_1 + x_2 - 2x_3 \leq -1, \;\; x_1, x_2, x_3 \geq 0.</span></p>
<p>Here <span class="math inline">b = (4, -5, -1)^\top</span>, so <span class="math inline">b_2 = -5 &lt; 0</span> and <span class="math inline">b_3 = -1 &lt; 0</span>. The slack-variable basis gives <span class="math inline">x_B = b</span>, which has negative entries – we cannot start simplex directly.</p>
<p><strong>Construct the Aux-LP.</strong> Subtract <span class="math inline">x_0</span> from each constraint:</p>
<p><span class="math display">\min \; x_0 \quad \text{s.t.} \quad 2x_1 - x_2 + 2x_3 - x_0 \leq 4, \;\; 2x_1 - 3x_2 + x_3 - x_0 \leq -5, \;\; -x_1 + x_2 - 2x_3 - x_0 \leq -1, \;\; x_0, x_1, x_2, x_3 \geq 0.</span></p>
<p><strong>Find a starting BFS for the Aux-LP.</strong> Set <span class="math inline">x_1 = x_2 = x_3 = 0</span> and <span class="math inline">x_0 = -\min_i b_i = -(-5) = 5</span>. Adding slack variables <span class="math inline">s_1, s_2, s_3</span>:</p>
<p><span class="math display">s_1 = 4 + 5 = 9, \qquad s_2 = -5 + 5 = 0, \qquad s_3 = -1 + 5 = 4.</span></p>
<p>Since <span class="math inline">s_2 = 0</span>, the initial basis for the Aux-LP is <span class="math inline">B = \{x_0, s_1, s_3\}</span> (we replace <span class="math inline">s_2</span> with <span class="math inline">x_0</span>). This is a valid BFS: all basic variables are nonneg (<span class="math inline">x_0 = 5, s_1 = 9, s_3 = 4</span>).</p>
<p><strong>Solve the Aux-LP.</strong> In equational form with slack variables, the Aux-LP constraints are:</p>
<p><span class="math display">\begin{aligned}
2x_1 - x_2 + 2x_3 - x_0 + s_1 &amp;= 4, \\
2x_1 - 3x_2 + x_3 - x_0 + s_2 &amp;= -5, \\
-x_1 + x_2 - 2x_3 - x_0 + s_3 &amp;= -1.
\end{aligned}</span></p>
<p>The objective is <span class="math inline">\min x_0</span>. Since <span class="math inline">x_0</span> is basic, we express the objective in terms of non-basic variables by using the second row (where <span class="math inline">x_0</span> entered) to eliminate <span class="math inline">x_0</span>:</p>
<p><span class="math display">x_0 = 2x_1 - 3x_2 + x_3 - s_2 - 5 \quad \Longrightarrow \quad z = x_0 = 5 + (2x_1 - 3x_2 + x_3 - s_2).</span></p>
<p>Reading off the reduced costs: <span class="math inline">r_{x_1} = 2</span>, <span class="math inline">r_{x_2} = -3</span>, <span class="math inline">r_{x_3} = 1</span>, <span class="math inline">r_{s_2} = -1</span>. Since <span class="math inline">r_{x_2} = -3 &lt; 0</span>, variable <span class="math inline">x_2</span> should enter the basis. The simplex method proceeds from here, pivoting to decrease <span class="math inline">x_0</span> until (if possible) <span class="math inline">x_0 = 0</span>.</p>
<p><strong>Interpret the result.</strong> If simplex drives <span class="math inline">x_0^*</span> to zero, the accompanying values of <span class="math inline">(x_1, x_2, x_3, s_1, s_2, s_3)</span> form a BFS for the original LP. We then switch the objective back to <span class="math inline">\min(-x_1 + x_2 - x_3)</span> and continue simplex from this starting BFS. If instead <span class="math inline">x_0^* &gt; 0</span> at optimality, the original LP is infeasible — no assignment of <span class="math inline">x_1, x_2, x_3 \geq 0</span> can satisfy all the original constraints.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two-Phase Simplex
</div>
</div>
<div class="callout-body-container callout-body">
<p>The procedure above is often called the <strong>two-phase simplex method</strong>:</p>
<ul>
<li><strong>Phase I:</strong> Solve the Aux-LP to find a feasible BFS (or detect infeasibility).</li>
<li><strong>Phase II:</strong> Starting from that BFS, solve the original LP.</li>
</ul>
<p>The two phases use exactly the same simplex machinery — the only difference is the objective function. Phase I minimizes the artificial variable <span class="math inline">x_0</span>; Phase II minimizes the original cost <span class="math inline">c^\top x</span>.</p>
</div>
</div>
<p>With the auxiliary LP, we can now initialize the simplex method on any LP — the last remaining gap in the algorithm. The final design choice is the pivoting rule: among all non-basic variables with negative relative cost, which one should enter the basis? This choice turns out to have deep implications for whether the algorithm terminates at all.</p>
</section>
</section>
<section id="sec-pivoting-rules" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="sec-pivoting-rules"><span class="header-section-number">10.7</span> Pivoting Rules</h2>
<p>The simplex algorithm leaves freedom in <strong>Step 3</strong>: how to choose the entering variable <span class="math inline">q</span> among all non-basic variables with negative relative cost. Different choices lead to different pivoting rules, with significant implications for termination and performance.</p>
<section id="sec-dantzig" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="sec-dantzig"><span class="header-section-number">10.7.1</span> Dantzig’s Rule</h3>
<div id="def-dantzig-rule" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.5 (Dantzig’s Pivoting Rule)</strong></span> <strong>Entering variable:</strong> Choose the non-basic variable with the <strong>most negative</strong> relative cost:</p>
<p><span class="math display">q = \arg\min_{j \in N} \left\{\widetilde{c}_j : \widetilde{c}_j &lt; 0\right\}.</span></p>
<p><strong>Leaving variable:</strong> Perform the ratio test (<a href="#eq-ratio-test" class="quarto-xref">Equation&nbsp;<span>10.6</span></a>). If there are ties, break by choosing the <strong>smallest index</strong>:</p>
<p><span class="math display">p = \arg\min_{i \in B} \left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0\right\}.</span></p>
</div>
<p>Dantzig’s rule is intuitive: pick the variable that decreases the objective the fastest (per unit increase). However, it has a serious flaw.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Dantzig’s Rule Can Cycle
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unfortunately, the simplex method with Dantzig’s rule <strong>can run forever</strong>. In degenerate cases, it will cycle among a few extreme points with equal objective value, never terminating.</p>
</div>
</div>
</section>
<section id="sec-degeneracy" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="sec-degeneracy"><span class="header-section-number">10.7.2</span> Degeneracy and Cycling</h3>
<div id="def-degeneracy" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.6 (Degeneracy)</strong></span> A BFS is <strong>degenerate</strong> if some basic variable has value zero, i.e., <span class="math inline">\widetilde{b}_i = 0</span> for some <span class="math inline">i \in B</span> (equivalently, <span class="math inline">x_B^*</span> contains a zero entry).</p>
</div>
<p>When a BFS is degenerate, a pivot may produce <span class="math inline">t^* = 0</span>, meaning the objective does not improve. The basis changes but the BFS point does not move. If a sequence of such zero-step pivots returns to a previously visited basis, the algorithm <strong>cycles</strong> and never terminates.</p>
<div id="exm-cycling" class="theorem example">
<p><span class="theorem-title"><strong>Example 10.3 (A Cycling Example)</strong></span> The following LP (from Beale, adapted by Marshall) cycles under Dantzig’s rule:</p>
<p><span class="math display">\max \; \zeta = 10x_1 - 57x_2 - 9x_3 - 24x_4 \quad \text{s.t.}</span> <span class="math display">0.5x_1 - 5.5x_2 - 2.5x_3 + 9x_4 \leq 0,</span> <span class="math display">0.5x_1 - 1.5x_2 - 0.5x_3 + x_4 \leq 0,</span> <span class="math display">x_1 \leq 1,</span> <span class="math display">x_1, x_2, x_3, x_4 \geq 0.</span></p>
<p>The initial BFS has <span class="math inline">\widetilde{b}_1 = \widetilde{b}_2 = 0</span> (degenerate). Under Dantzig’s rule, the simplex method cycles through a sequence of bases, returning to the starting basis without improving the objective.</p>
</div>
<div id="thm-cycling" class="theorem">
<p><span class="theorem-title"><strong>Theorem 10.1 (Cycling and Non-Termination)</strong></span> If the simplex method fails to terminate, then it must cycle – that is, it revisits the same basis.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The number of possible bases is finite (at most <span class="math inline">\binom{n+m}{m}</span>). If the algorithm does not terminate, it must visit some basis twice. Since the simplex method is deterministic given a pivot rule, once it revisits a basis, it will repeat the same sequence of pivots indefinitely. <span class="math inline">\blacksquare</span></p>
</div>
</section>
<section id="sec-bland" class="level3" data-number="10.7.3">
<h3 data-number="10.7.3" class="anchored" data-anchor-id="sec-bland"><span class="header-section-number">10.7.3</span> Bland’s Rule</h3>
<p>Since Dantzig’s rule can cycle, we need a pivoting rule that guarantees termination. Bland’s rule resolves the cycling problem by using a simple, deterministic tie-breaking strategy: always choose the variable with the <strong>smallest index</strong>.</p>
<div id="def-bland-rule" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 10.7 (Bland’s Pivoting Rule)</strong></span> <strong>Entering variable:</strong> Choose the non-basic variable with <strong>smallest index</strong> among those with negative relative cost:</p>
<p><span class="math display">q = \min\left\{j \in N : \widetilde{c}_j &lt; 0\right\}.</span></p>
<p><strong>Leaving variable:</strong> Perform the ratio test (<a href="#eq-ratio-test" class="quarto-xref">Equation&nbsp;<span>10.6</span></a>). If there are ties, break by choosing the <strong>smallest index</strong>:</p>
<p><span class="math display">p = \arg\min_{i \in B}\left\{\frac{\widetilde{b}_i}{\widetilde{A}_{iq}} : \widetilde{A}_{iq} &gt; 0\right\}, \quad \text{with ties broken by smallest } i.</span></p>
</div>
<div id="thm-bland-termination" class="theorem">
<p><span class="theorem-title"><strong>Theorem 10.2 (Bland’s Rule Guarantees Termination)</strong></span> The simplex method with Bland’s rule <strong>always terminates</strong>.</p>
</div>
<p>This is a remarkable result. The simple prescription “choose the smallest index” is enough to break all possible cycling patterns, regardless of how degenerate the LP is.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Bland’s Rule vs.&nbsp;Dantzig’s Rule
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Dantzig’s Rule</th>
<th>Bland’s Rule</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Entering variable</strong></td>
<td>Most negative <span class="math inline">\widetilde{c}_j</span></td>
<td>Smallest index with <span class="math inline">\widetilde{c}_j &lt; 0</span></td>
</tr>
<tr class="even">
<td><strong>Tie-breaking</strong></td>
<td>Smallest index</td>
<td>Smallest index</td>
</tr>
<tr class="odd">
<td><strong>Termination</strong></td>
<td>Not guaranteed (can cycle)</td>
<td>Always terminates</td>
</tr>
<tr class="even">
<td><strong>Practice</strong></td>
<td>Often faster per iteration</td>
<td>Slower but safe</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Bland’s rule resolves the termination question: the simplex method always finishes in finitely many steps. But “finite” is a weak guarantee — it says nothing about whether the algorithm is efficient. The natural next question is: how many pivots does the simplex method require as a function of the problem size?</p>
</section>
<section id="sec-oracle-complexity" class="level3" data-number="10.7.4">
<h3 data-number="10.7.4" class="anchored" data-anchor-id="sec-oracle-complexity"><span class="header-section-number">10.7.4</span> Oracle Complexity</h3>
<p>To analyze the efficiency of the simplex method, we use the <strong>oracle computational model</strong>.</p>
<section id="sec-oracle-model" class="level4" data-number="10.7.4.1">
<h4 data-number="10.7.4.1" class="anchored" data-anchor-id="sec-oracle-model"><span class="header-section-number">10.7.4.1</span> The Oracle Model</h4>
<p>In the oracle model, an iterative algorithm interacts with an <strong>oracle</strong> that provides information for each update:</p>
<ul>
<li>The <strong>simplex algorithm</strong> maintains the current basis <span class="math inline">B</span>.</li>
<li>At each iteration, it queries the oracle with the basis <span class="math inline">B</span>.</li>
<li>The oracle returns <span class="math inline">\widetilde{b} = x_B^*</span> (the BFS), <span class="math inline">\widetilde{c}</span> (relative costs), and <span class="math inline">\widetilde{A}</span> (transformed constraints).</li>
<li>Using this information, the algorithm decides: (a) the pivot pair <span class="math inline">(p, q)</span>, (b) whether the LP is unbounded (<span class="math inline">\widetilde{A}_{iq} \leq 0</span> for all <span class="math inline">i</span>), or (c) whether to check feasibility via the Aux-LP.</li>
</ul>
<p>The <strong>oracle complexity</strong> is the number of queries (= the number of pivots):</p>
<p><span class="math display">\text{Oracle complexity} = \#\text{ queries of } \{\widetilde{b}, \widetilde{c}, \widetilde{A}\} = \#\text{ pivots } (p, q).</span></p>
</section>
<section id="sec-complexity-guarantee" class="level4" data-number="10.7.4.2">
<h4 data-number="10.7.4.2" class="anchored" data-anchor-id="sec-complexity-guarantee"><span class="header-section-number">10.7.4.2</span> Complexity Guarantee</h4>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>No Polynomial Bound Known
</div>
</div>
<div class="callout-body-container callout-body">
<p>With Bland’s rule, the simplex method is guaranteed to terminate in a <strong>finite</strong> number of pivots. However, we do not know how the number of pivots scales as a function of <span class="math inline">m</span> and <span class="math inline">n</span>.</p>
<p><strong>“No guarantee beyond finiteness.”</strong></p>
<p>The worst-case number of pivots can be exponential (e.g., the Klee-Minty cube requires <span class="math inline">2^n - 1</span> pivots with certain pivot rules). Whether there exists a pivot rule that guarantees a polynomial number of pivots remains one of the major open questions in optimization.</p>
</div>
</div>
<p>Despite this worst-case behavior, the simplex method is remarkably efficient in practice. Empirically, the number of pivots is typically <span class="math inline">O(m)</span> to <span class="math inline">O(m \log n)</span> – far from the exponential worst case. This practical efficiency, combined with the method’s ability to exploit problem structure and warm-start from nearby solutions, is why simplex remains the algorithm of choice for most LP solvers.</p>
</section>
</section>
</section>
<section id="sec-step-by-step" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="sec-step-by-step"><span class="header-section-number">10.8</span> Simplex Method Step by Step</h2>
<p>The following visualization traces the simplex method step by step on the worked example. Use the slider to advance through iterations and observe how the entering and leaving variable selection drives the algorithm from one BFS to the next.</p>
<div id="fig-simplex-interactive" style="width:100%;max-width:700px;margin:auto;"></div>
<p class="figure-caption" style="text-align:center;margin-top:0.5em;">Figure 10.4: Interactive simplex method demo. Use the slider to step through pivot iterations. The red arrow shows the direction of movement, and the highlighted vertex is the current BFS.</p>
<script>
(function() {
  var poly_x = [0, 2, 0.5, 0, 0];
  var poly_y = [0, 0, 1.5, 1, 0];

  var path = [
    {label: 'e', x: 0, y: 0, B: '{3,4}', obj: 0,
     desc: 'Start: BFS e at origin.<br>c\u0303 = (0, \u22121). Enter q=2, leave p=3.'},
    {label: 'd', x: 0, y: 1, B: '{2,4}', obj: -1,
     desc: 'After pivot (3,2): BFS d.<br>c\u0303 = (\u22121, 1). Enter q=1, leave p=4.'},
    {label: 'a', x: 0.5, y: 1.5, B: '{1,2}', obj: -1.5,
     desc: 'After pivot (4,1): BFS a.<br>c\u0303 = (0.5, 0.5) \u2265 0. OPTIMAL!'}
  ];

  var xx = Array.from({length: 50}, function(_, i) { return -0.5 + 3.5 * i / 49; });

  var frames = [];
  for (var step = 0; step < path.length; step++) {
    var frameData = [];

    // Feasible region
    frameData.push({x: poly_x, y: poly_y, fill: 'toself',
      fillcolor: 'rgba(123,143,163,0.15)', line: {color: '#7b97ad', width: 2.5},
      name: 'Feasible region', mode: 'lines'});

    // Constraint lines
    frameData.push({x: xx, y: xx.map(function(v){return v+1;}), mode: 'lines',
      line: {color: '#968a80', dash: 'dot', width: 1}, showlegend: false, hoverinfo: 'skip'});
    frameData.push({x: xx, y: xx.map(function(v){return 2-v;}), mode: 'lines',
      line: {color: '#968a80', dash: 'dot', width: 1}, showlegend: false, hoverinfo: 'skip'});

    // Other BFS (gray)
    frameData.push({x: [2], y: [0], mode: 'markers+text',
      marker: {color: '#aaa', size: 7}, text: ['b'],
      textposition: 'bottom right', textfont: {size: 10, color: '#aaa'},
      showlegend: false, hoverinfo: 'skip'});

    // Visited path so far
    var px = [], py = [];
    for (var k = 0; k <= step; k++) { px.push(path[k].x); py.push(path[k].y); }
    frameData.push({x: px, y: py, mode: 'lines',
      line: {color: '#b56b6b', width: 3}, name: 'Simplex path', showlegend: false});

    // Visited vertices
    for (var k = 0; k <= step; k++) {
      var p = path[k];
      var isCurrent = (k === step);
      var sz = isCurrent ? 14 : 8;
      var sym = (isCurrent && step === path.length-1) ? 'star' : (isCurrent ? 'diamond' : 'circle');
      var col = isCurrent ? '#b56b6b' : '#8a6e5e';
      frameData.push({x: [p.x], y: [p.y], mode: 'markers+text',
        marker: {color: col, size: sz, symbol: sym, line: {width: 1.5, color: 'white'}},
        text: [p.label], textposition: 'top left',
        textfont: {size: 12, color: col},
        hovertext: ['BFS ' + p.label + ': (' + p.x + ',' + p.y + ')<br>B=' + p.B + ', \u03b6=' + p.obj],
        hoverinfo: 'text', showlegend: false});
    }

    // Annotations
    var anns = [];
    if (step < path.length - 1) {
      anns.push({x: path[step+1].x, y: path[step+1].y,
        ax: path[step].x, ay: path[step].y,
        xref: 'x', yref: 'y', axref: 'x', ayref: 'y',
        showarrow: true, arrowhead: 3, arrowsize: 1.5, arrowcolor: '#b56b6b', arrowwidth: 2});
    }
    anns.push({x: 0.02, y: 0.02, xref: 'paper', yref: 'paper',
      text: '<b>Step ' + step + ': B=' + path[step].B + ', \u03b6=' + path[step].obj + '</b><br>' + path[step].desc,
      showarrow: false, font: {size: 11}, align: 'left',
      bgcolor: 'rgba(255,255,255,0.85)', bordercolor: '#7b97ad', borderwidth: 1});

    frames.push({data: frameData, name: String(step), layout: {annotations: anns}});
  }

  var sliderSteps = [];
  for (var k = 0; k < frames.length; k++) {
    sliderSteps.push({args: [[String(k)], {mode: 'immediate', frame: {duration: 0, redraw: true}}],
      label: 'Step ' + k, method: 'animate'});
  }

  var layout = themeLayout({
    xaxis: themeAxis('x\u2081', {range: [-0.5, 2.8], zeroline: true, showline: true}),
    yaxis: themeAxis('x\u2082', {range: [-0.5, 2.3], zeroline: true, scaleanchor: 'x', showline: true}),
    showlegend: false,
    annotations: frames[0].layout.annotations,
    margin: {t: 20, b: 70, l: 55, r: 20},
    sliders: [{active: 0, pad: {t: 40}, steps: sliderSteps,
      currentvalue: {prefix: '', visible: true}, x: 0.1, len: 0.8}]
  });

  Plotly.newPlot('fig-simplex-interactive', frames[0].data, layout, plotlyConfig)
    .then(function() { return Plotly.addFrames('fig-simplex-interactive', frames); });
})();
</script>
</section>
<section id="sec-summary" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="sec-summary"><span class="header-section-number">10.9</span> Summary</h2>
<p>The simplex method is a complete algorithm for linear programming. Let us recap its key components:</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Simplex Method: Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>How to decide that an LP is feasible?</strong> Solve the Aux-LP. The original LP is feasible if and only if the optimal value of the Aux-LP equals zero.</p></li>
<li><p><strong>How to initialize the simplex method?</strong> If <span class="math inline">b \geq 0</span>, use the slack-variable basis. Otherwise, solve the Aux-LP – its optimal BFS provides the starting basis.</p></li>
<li><p><strong>How to decide the entering and leaving variables?</strong> Use a pivoting rule:</p>
<ul>
<li><strong>Bland’s rule</strong>: smallest index with negative relative cost (for entering); ratio test with smallest-index tie-breaking (for leaving).</li>
</ul></li>
<li><p><strong>How to detect unboundedness?</strong> During the ratio test: if <span class="math inline">\widetilde{A}_{iq} \leq 0</span> for all <span class="math inline">i \in B</span>, the LP is unbounded.</p></li>
<li><p><strong>Does simplex terminate?</strong> Yes, using Bland’s rule. But with no known polynomial bound on the number of pivots – “no guarantee beyond finiteness.”</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Looking Ahead
</div>
</div>
<div class="callout-body-container callout-body">
<p>The simplex method is extraordinarily effective in practice, typically solving LPs in <span class="math inline">O(m)</span> to <span class="math inline">O(m \log n)</span> pivots. However, its worst-case exponential complexity motivates the search for algorithms with provably polynomial guarantees. In the next chapter, we study <strong>interior point methods</strong>, which achieve polynomial-time complexity by traversing the interior of the feasible region rather than its boundary.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../lectures/09-lp-formulation-geometry.html" class="pagination-link" aria-label="LP Formulation and Geometry">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">LP Formulation and Geometry</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../lectures/11-lp-duality.html" class="pagination-link" aria-label="LP Duality">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">LP Duality</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>